language: go

go:
    - 1.7.x
    - tip

matrix:
    allow_failures:
        - go: tip

install:
  - rm -rf $GOPATH/src/srcd.works
  - mkdir -p $GOPATH/src/srcd.works
  - ln -s $PWD $GOPATH/src/srcd.works/go-errors.v0
  - cd $GOPATH/src/srcd.works/go-errors.v0
  - go get -v -t ./...

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)